; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Instrument 1
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $f9, $f9, $ab, $f9, $f9, $ab, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref15:
	.byte $32, $8f, $32, $8f, $40, $8f, $3a, $8f, $32, $8f, $32, $8f, $40, $8f, $3a, $8f
	.byte $ff, $10
	.word @song0ref15
@song0ref34:
	.byte $36, $8f, $36, $8f, $44, $8f, $40, $8f, $36, $8f, $36, $8f, $44, $8f, $40, $8f
	.byte $ff, $10
	.word @song0ref34
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref58:
	.byte $32, $8f, $00, $8f, $32, $8f, $00, $8f, $32, $8f, $00, $8f
	.byte $ff, $0c
	.word @song0ref58
	.byte $32, $8f, $00, $8f, $32
@song0ref78:
	.byte $8f, $00, $8f, $36, $8f, $00, $8f, $36, $8f, $00, $8f, $36
	.byte $ff, $0c
	.word @song0ref78
	.byte $ff, $0b
	.word @song0ref78
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref101:
	.byte $4a, $8f, $78, $8f, $4a, $8f, $4a, $8f, $78, $8f, $4a, $8f, $78, $8f, $4a, $8f, $4a, $8f, $78, $8f
	.byte $ff, $0c
	.word @song0ref101
	.byte $ff, $14
	.word @song0ref101
	.byte $ff, $0c
	.word @song0ref101
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $f9, $f9, $ab, $f9, $f9, $ab, $fd
	.word @song0ch4loop
